
const sourceData = {"sources": [
    { "interface": "website", "source": "liveuamap.com", "id": 1, "image": null, "headline": null, "text": "Clashes and artillery shelling in Trostyanets, fires burning", "language": "en", "timestamp": 1647903600, "locations": [{ "name": "Trostyanets", "lat": 47.6054743, "lng": 29.259883 }] },
    { "interface": "website", "source": "liveuamap.com", "id": 2, "image": "https://placekitten.com/200/200", "headline": null, "text": "Emergency situation regime introduced in two villages of the Bilhorod region due to a shell explosion. Emergency situation regime introduced in two villages of the Bilhorod region due to a shell explosion. Emergency situation regime introduced in two villages of the Bilhorod region due to a shell explosion. Emergency situation regime introduced in two villages of the Bilhorod region due to a shell explosion.", "language": "en", "timestamp": 1648044000, "locations": [{ "name": "Bilhorod", "lat": 46.1909823, "lng": 30.345784 }] },
    { "interface": "website", "source": "liveuamap.com", "id": 3, "image": null, "headline": null, "text": "Російські військові обстріляли з артилерії одне з харчових підприємств у Чернігові. Стався витік аміаку, проте його концентрація в межах допустимої норми, розповів Суспільному голова ОВА Чаус", "language": "ua", "timestamp": 1647990000, "locations": [{ "name": "Чернігові", "lat": 51.498392100000004, "lng": 31.291385200000008 }] },
    { "interface": "website", "source": "maphub.net", "id": 4, "image": null, "headline": null, "text": "Another video with a captured T-80U and two T-80BV tanks.", "language": "en", "timestamp": 1648076400, "locations": [] },
    { "interface": "website", "source": "somenewssite.net", "id": 5, "image": "https://placekitten.com/500/300", "headline": null, "text": "В столице Болгарии Софии прошло массовое шествие в поддержку Украины.", "language": "ru", "timestamp": 1648162800, "locations": [{ "name": "Болгарии", "lat": 42.6073975, "lng": 25.4856617 }, { "name": "Софии", "lat": 42.6978634, "lng": 23.3221789 }, { "name": "Украины", "lat": 49.7647222, "lng": 21.1288889 }] },
    { "interface": "twitter", "source": "twitter.com", "id": 6, "image": null, "headline": null, "text": "This is a tweet.", "language": "en", "timestamp": 1647903600, "locations": [{ "name": "Trostyanets", "lat": 48.6054743, "lng": 29.259883 }] },
    { "interface": "twitter", "source": "twitter.com", "id": 7, "image": null, "headline": null, "text": "This is a tweet.", "language": "en", "timestamp": 1647903600, "locations": [{ "name": "Trostyanets", "lat": 48.6054743, "lng": 26.259883 }] },
    { "interface": "twitter", "source": "twitter.com", "id": 8, "image": null, "headline": null, "text": "This is a tweet.", "language": "en", "timestamp": 1647903600, "locations": [{ "name": "Trostyanets", "lat": 48.6054743, "lng": 27.259883 }] },
    { "interface": "twitter", "source": "twitter.com", "id": 9, "image": null, "headline": null, "text": "This is a tweet.", "language": "en", "timestamp": 1647903600, "locations": [{ "name": "Trostyanets", "lat": 48.6054743, "lng": 28.259883 }] },
]}
    
export default sourceData